### ISSUE TITLE
Define a goal to present for the ags community

### ISSUE THREAD

**Issue by ericoporto** [ericoporto/agshelp#12]
We need some roadmap. If this new help will become the official help, some requirements have to be met. This is an issue to register these goals. They have to be achievable in a short timeframe. Once some requirements are met, we should propose this help as alternative to current help.

**Comment by ivan-mogilko** [comment]
My opinion here: as fast as possible, as soon as
- the text is proofread and confirmed formatted correctly;
- there is an establish procedure to create both online and offline manual in acceptable form (e.g. CHM, to be able to use it without modifying Editor's context help command).

I would love to edit a new help already if there is a need to update it for release.

On a side note, I have noticed there is already a  bunch of issue tickets hanging here, while there is a repository created specifically for the manual in the community group: https://github.com/adventuregamestudio/ags-manual

Would it be possible to migrate there, before much more tickets and pull requests become opened?
I can give necessary permissions to everyone involved.

**Comment by ericoporto** [comment]
@ivan-mogilko I don't see any problem to migrate the repository to there, I thought you would prefer we wrote more things, but no problem at all! It would be amazing! I will add you here, maybe this helps!

**Comment by ivan-mogilko** [comment]
But what would *you* need to recreate same content in that repository? I don't know whether I'd need to be invited here?

**Comment by ericoporto** [comment]
Hey, we solved this already, it's in the repo here: https://github.com/adventuregamestudio/ags-manual

We can move discussion there!
